export const STARTER_ROLE_SEED_EN = {
  1: {
    nume: "Emma Carter",
    titlu: "Cashier / Sales Assistant",
    email: "emma.carter@example.com",
    telefon: "+44 7700 123456",
    oras: "London",
    linkedin: "linkedin.com/in/emma-carter-cashier",
    despre: "Cashier with 4 years of experience in fast-paced retail stores. Known for accurate payment handling, friendly customer service, and steady performance during peak hours.",
    experienta: [
      {
        firma: "CityMart",
        perioada: "2022 - Present",
        rol: "Senior Cashier",
        desc: "Process 180+ transactions per shift with 99.8% accuracy • Resolve customer questions quickly and calmly • Support onboarding for new team members on POS and checkout routines",
      },
      {
        firma: "FreshBasket",
        perioada: "2020 - 2022",
        rol: "Cashier",
        desc: "Handled cash, card, and mobile payments in a high-volume environment • Maintained a clean and organized checkout area • Helped improve loyalty sign-ups through customer-facing promotions",
      },
    ],
    educatie: [
      {
        institutie: "Southbank College",
        perioada: "2017 - 2020",
        diploma: "Diploma in Retail Operations",
      },
    ],
    competente: ["POS systems", "Cash handling", "Customer service", "Upselling", "Inventory support", "Teamwork"],
    limbi: ["English (native)", "Spanish (intermediate)"],
    certificari: ["Retail Customer Service Certificate", "POS Operations Training"],
  },
  2: {
    nume: "Olivia Hayes",
    titlu: "Secretary / Administrative Assistant",
    email: "olivia.hayes@example.com",
    telefon: "+353 87 555 1010",
    oras: "Dublin",
    linkedin: "linkedin.com/in/olivia-hayes-admin",
    despre: "Administrative professional with 6 years of experience supporting executives in legal and corporate environments. Strong in calendar management, documentation, and communication across teams.",
    experienta: [
      {
        firma: "NorthBridge Capital",
        perioada: "2021 - Present",
        rol: "Executive Secretary",
        desc: "Coordinate complex executive calendars and travel schedules • Prepare meeting materials and confidential reports • Organize internal events and maintain documentation workflows",
      },
      {
        firma: "Harrison Legal",
        perioada: "2018 - 2021",
        rol: "Administrative Assistant",
        desc: "Managed client appointments and legal documentation • Drafted professional correspondence and formatted contracts • Supported a team of 7 lawyers with day-to-day operations",
      },
    ],
    educatie: [
      {
        institutie: "Dublin Business School",
        perioada: "2014 - 2018",
        diploma: "Bachelor's Degree in Business Administration",
      },
    ],
    competente: ["Executive scheduling", "Office administration", "Document control", "Meeting coordination", "MS Office", "Professional communication"],
    limbi: ["English (native)", "French (upper intermediate)"],
    certificari: ["Administrative Professional Certificate", "Business Writing Workshop"],
  },
  3: {
    nume: "Noah Brooks",
    titlu: "Retail Assistant / Sales Associate",
    email: "noah.brooks@example.com",
    telefon: "+31 6 1822 3344",
    oras: "Amsterdam",
    linkedin: "linkedin.com/in/noah-brooks-retail",
    despre: "Retail associate with 5 years of experience in customer-facing sales and merchandising. Motivated by store performance, product presentation, and delivering a smooth in-store experience.",
    experienta: [
      {
        firma: "Urban Market",
        perioada: "2022 - Present",
        rol: "Senior Retail Assistant",
        desc: "Maintain product displays and replenish stock across key departments • Exceed monthly sales goals through active customer support • Mentor new hires on store routines and merchandising standards",
      },
      {
        firma: "HomeStyle Store",
        perioada: "2019 - 2022",
        rol: "Sales Associate",
        desc: "Supported customers with product recommendations and add-on sales • Assisted with stock checks, deliveries, and inventory counts • Helped improve shelf availability and visual consistency",
      },
    ],
    educatie: [
      {
        institutie: "Amsterdam College of Commerce",
        perioada: "2015 - 2019",
        diploma: "Diploma in Retail and Sales",
      },
    ],
    competente: ["Merchandising", "Sales support", "Stock control", "Customer relations", "Store presentation", "Time management"],
    limbi: ["English (fluent)", "Dutch (native)"],
    certificari: ["Retail Sales Certificate", "Visual Merchandising Workshop"],
  },
  4: {
    nume: "Sophia Reed",
    titlu: "HR Specialist / Recruiter",
    email: "sophia.reed@example.com",
    telefon: "+49 151 2200 3344",
    oras: "Berlin",
    linkedin: "linkedin.com/in/sophia-reed-hr",
    despre: "HR specialist with 7 years of experience in recruitment, employee lifecycle operations, and performance support. Skilled at hiring for both business and technical roles in growing teams.",
    experienta: [
      {
        firma: "BrightScale",
        perioada: "2021 - Present",
        rol: "Senior HR Business Partner",
        desc: "Lead end-to-end hiring for commercial and product teams • Improve onboarding and manager support processes • Track recruitment metrics and partner with leaders on headcount planning",
      },
      {
        firma: "BlueStone Consulting",
        perioada: "2017 - 2021",
        rol: "Recruiter",
        desc: "Managed sourcing, interviews, and offers for 90+ roles per year • Built talent pipelines through LinkedIn and referrals • Supported employer branding and candidate experience initiatives",
      },
    ],
    educatie: [
      {
        institutie: "University of Leeds",
        perioada: "2013 - 2016",
        diploma: "Bachelor's Degree in Human Resource Management",
      },
    ],
    competente: ["Full-cycle recruitment", "HR operations", "Stakeholder management", "Applicant tracking systems", "Employer branding", "People analytics"],
    limbi: ["English (native)", "German (intermediate)"],
    certificari: ["SHRM-CP", "LinkedIn Recruiter Certification"],
  },
  5: {
    nume: "Ethan Miller",
    titlu: "Data Entry Operator / Data Specialist",
    email: "ethan.miller@example.com",
    telefon: "+1 415 555 2040",
    oras: "Chicago",
    linkedin: "linkedin.com/in/ethan-miller-data",
    despre: "Data specialist with 5 years of experience entering, validating, and organizing large data volumes with high accuracy. Strong in spreadsheets, databases, and structured quality checks.",
    experienta: [
      {
        firma: "NorthCore Analytics",
        perioada: "2022 - Present",
        rol: "Senior Data Entry Operator",
        desc: "Process and validate 4,000+ records per day with strong quality standards • Build Excel reports for weekly operations reviews • Support internal users with data clean-up and updates",
      },
      {
        firma: "TeleCom One",
        perioada: "2019 - 2022",
        rol: "Data Entry Specialist",
        desc: "Entered customer and billing data into CRM and ERP systems • Investigated mismatched records and corrected inconsistencies • Maintained document archives and process logs",
      },
    ],
    educatie: [
      {
        institutie: "Illinois State University",
        perioada: "2015 - 2019",
        diploma: "Bachelor's Degree in Information Systems",
      },
    ],
    competente: ["Excel reporting", "Database entry", "Data validation", "ERP systems", "Typing speed", "Attention to detail"],
    limbi: ["English (native)", "Spanish (intermediate)"],
    certificari: ["Microsoft Office Specialist - Excel", "Data Quality Essentials Certificate"],
  },
  6: {
    nume: "Grace Turner",
    titlu: "Executive Assistant / Office Manager",
    email: "grace.turner@example.com",
    telefon: "+61 412 555 880",
    oras: "Sydney",
    linkedin: "linkedin.com/in/grace-turner-executive-assistant",
    despre: "Executive assistant with 6 years of experience supporting senior leadership and coordinating office operations. Trusted to keep priorities moving, manage logistics, and improve administrative processes.",
    experienta: [
      {
        firma: "Summit Logistics",
        perioada: "2021 - Present",
        rol: "Executive Assistant to the COO",
        desc: "Manage calendars, travel, and executive meeting preparation • Coordinate cross-functional projects and follow-ups • Improve document workflows and vendor communication across the office",
      },
      {
        firma: "Helios Manufacturing",
        perioada: "2018 - 2021",
        rol: "Office Manager",
        desc: "Oversaw office operations, purchasing, and supplier coordination • Prepared monthly management reports and presentation decks • Supported internal events and cross-team planning",
      },
    ],
    educatie: [
      {
        institutie: "Macquarie University",
        perioada: "2014 - 2017",
        diploma: "Bachelor's Degree in Management",
      },
    ],
    competente: ["Executive support", "Project coordination", "Calendar management", "Vendor management", "Reporting", "Process improvement"],
    limbi: ["English (native)", "Italian (intermediate)"],
    certificari: ["Project Coordination Certificate", "Office Management Professional"],
  },
  7: {
    nume: "Chloe Bennett",
    titlu: "Registered Nurse",
    email: "chloe.bennett@example.com",
    telefon: "+44 7711 908070",
    oras: "Manchester",
    linkedin: "linkedin.com/in/chloe-bennett-rn",
    despre: "Registered nurse with 8 years of experience in inpatient care, emergency support, and patient monitoring. Committed to safe care delivery, teamwork, and calm communication in high-pressure settings.",
    experienta: [
      {
        firma: "Northside Medical Center",
        perioada: "2020 - Present",
        rol: "Senior Registered Nurse",
        desc: "Monitor patients across busy medical units and coordinate shift handovers • Administer medication and document care accurately • Support junior nurses and maintain infection control standards",
      },
      {
        firma: "Riverside Hospital",
        perioada: "2016 - 2020",
        rol: "Registered Nurse",
        desc: "Provided bedside care, patient education, and discharge support • Assisted physicians during procedures and urgent interventions • Maintained clear records in electronic medical systems",
      },
    ],
    educatie: [
      {
        institutie: "University of Manchester",
        perioada: "2012 - 2015",
        diploma: "Bachelor of Science in Nursing",
      },
    ],
    competente: ["Patient care", "Medication administration", "Vital signs monitoring", "Emergency response", "Clinical documentation", "Empathetic communication"],
    limbi: ["English (native)", "French (basic)"],
    certificari: ["BLS Certification", "Advanced Life Support Training"],
  },
  8: {
    nume: "Dr. Daniel Foster",
    titlu: "Internal Medicine Specialist",
    email: "daniel.foster@example.com",
    telefon: "+1 646 555 3201",
    oras: "New York",
    linkedin: "linkedin.com/in/dr-daniel-foster",
    despre: "Internal medicine physician with 12 years of clinical experience in diagnostics, chronic disease management, and patient-centered care. Comfortable leading multidisciplinary collaboration in hospital and outpatient settings.",
    experienta: [
      {
        firma: "University Medical Center",
        perioada: "2019 - Present",
        rol: "Internal Medicine Specialist",
        desc: "Assess and manage complex adult cases across inpatient and outpatient care • Interpret diagnostics and coordinate treatment plans with specialty teams • Contribute to quality improvement and resident mentoring",
      },
      {
        firma: "Harbor Clinic",
        perioada: "2014 - 2019",
        rol: "Attending Physician",
        desc: "Provided consultations for internal medicine and preventive care patients • Managed chronic disease follow-up and evidence-based treatment plans • Participated in clinical research and continuing education programs",
      },
    ],
    educatie: [
      {
        institutie: "Columbia University",
        perioada: "2006 - 2010",
        diploma: "Doctor of Medicine",
      },
      {
        institutie: "NewYork-Presbyterian Residency Program",
        perioada: "2010 - 2014",
        diploma: "Residency in Internal Medicine",
      },
    ],
    competente: ["Clinical diagnostics", "Chronic disease management", "Patient communication", "Care coordination", "Evidence-based medicine", "Medical documentation"],
    limbi: ["English (native)", "Spanish (professional)"],
    certificari: ["Board Certification in Internal Medicine", "Advanced Cardiac Life Support"],
  },
  9: {
    nume: "Mia Collins",
    titlu: "Math & Computer Science Teacher",
    email: "mia.collins@example.com",
    telefon: "+353 85 440 7788",
    oras: "Galway",
    linkedin: "linkedin.com/in/mia-collins-teacher",
    despre: "Teacher with 10 years of experience delivering mathematics and computer science lessons for secondary students. Focused on clear instruction, student engagement, and measurable exam performance.",
    experienta: [
      {
        firma: "Westfield High School",
        perioada: "2019 - Present",
        rol: "Mathematics Teacher",
        desc: "Teach secondary-level mathematics with strong exam preparation results • Create structured lesson plans and differentiated support • Lead STEM clubs and enrichment activities for advanced students",
      },
      {
        firma: "Oakridge Academy",
        perioada: "2014 - 2019",
        rol: "Computer Science Teacher",
        desc: "Delivered programming and digital literacy classes across upper grades • Introduced project-based learning and collaborative assignments • Supported students preparing for national competitions",
      },
    ],
    educatie: [
      {
        institutie: "National University of Ireland Galway",
        perioada: "2010 - 2014",
        diploma: "Bachelor's Degree in Mathematics and Computer Science",
      },
    ],
    competente: ["Lesson planning", "Classroom management", "STEM teaching", "Programming fundamentals", "Student assessment", "Parent communication"],
    limbi: ["English (native)", "Irish (basic)"],
    certificari: ["Qualified Teacher Status", "Google Certified Educator"],
  },
  10: {
    nume: "Lily Parker",
    titlu: "Call Center Agent / Customer Support",
    email: "lily.parker@example.com",
    telefon: "+1 303 555 6600",
    oras: "Denver",
    linkedin: "linkedin.com/in/lily-parker-support",
    despre: "Call center professional with 5 years of experience across inbound support, outbound follow-up, and complaint handling. Recognized for calm communication, fast issue resolution, and strong service metrics.",
    experienta: [
      {
        firma: "NovaTel",
        perioada: "2022 - Present",
        rol: "Senior Customer Care Agent",
        desc: "Handle 80+ customer calls per day while maintaining strong satisfaction scores • Support escalated cases and coach newer agents • Document outcomes clearly in CRM and ticketing tools",
      },
      {
        firma: "ConnectPlus",
        perioada: "2019 - 2022",
        rol: "Call Center Agent",
        desc: "Provided product, billing, and troubleshooting support over phone and email • Helped improve first-call resolution and call quality metrics • Supported service upgrades and retention campaigns",
      },
    ],
    educatie: [
      {
        institutie: "Colorado State University",
        perioada: "2015 - 2019",
        diploma: "Bachelor's Degree in Communications",
      },
    ],
    competente: ["Phone support", "Conflict resolution", "CRM systems", "Call handling", "Customer empathy", "KPI tracking"],
    limbi: ["English (native)", "Spanish (conversational)"],
    certificari: ["Customer Service Professional Certificate", "Contact Center Essentials"],
  },
  11: {
    nume: "James Walker",
    titlu: "Customer Support Specialist / Help Desk",
    email: "james.walker@example.com",
    telefon: "+49 170 998 2233",
    oras: "Munich",
    linkedin: "linkedin.com/in/james-walker-helpdesk",
    despre: "Customer support specialist with 4 years of experience helping users through chat, email, and ticketing platforms. Skilled at balancing fast response times with clear and thoughtful problem solving.",
    experienta: [
      {
        firma: "CloudDesk",
        perioada: "2022 - Present",
        rol: "Customer Support Specialist",
        desc: "Resolve product and account issues across chat and email channels • Maintain help center content and reusable troubleshooting guides • Partner with product teams to surface recurring issues",
      },
      {
        firma: "ShopSphere",
        perioada: "2020 - 2022",
        rol: "Support Agent",
        desc: "Handled order, returns, and account support for e-commerce users • Worked in Zendesk to triage and close tickets efficiently • Helped onboard new hires on support workflows and QA standards",
      },
    ],
    educatie: [
      {
        institutie: "University of Birmingham",
        perioada: "2016 - 2020",
        diploma: "Bachelor's Degree in Psychology",
      },
    ],
    competente: ["Zendesk", "Email support", "Live chat support", "Knowledge base writing", "Issue triage", "Clear communication"],
    limbi: ["English (native)", "German (intermediate)"],
    certificari: ["Zendesk Support Administrator", "Customer Experience Certificate"],
  },
  12: {
    nume: "Alexander Price",
    titlu: "Operations Manager / General Manager",
    email: "alexander.price@example.com",
    telefon: "+41 79 555 1188",
    oras: "Zurich",
    linkedin: "linkedin.com/in/alexander-price-operations",
    despre: "Operations leader with 12 years of experience scaling teams, improving margin, and delivering large business initiatives. Strong in planning, execution, and performance management across complex operations.",
    experienta: [
      {
        firma: "Vertex Foods",
        perioada: "2019 - Present",
        rol: "Operations Director",
        desc: "Lead multi-site operations with focus on productivity, cost control, and service quality • Partner with finance and supply chain on annual planning • Deliver process improvements and digital transformation projects",
      },
      {
        firma: "NorthPeak Operations",
        perioada: "2013 - 2019",
        rol: "Regional Operations Manager",
        desc: "Managed regional teams and site managers across production environments • Improved KPI visibility and standardized reporting • Oversaw hiring, budget ownership, and vendor performance reviews",
      },
    ],
    educatie: [
      {
        institutie: "University of Warwick",
        perioada: "2008 - 2011",
        diploma: "Bachelor's Degree in Industrial Engineering",
      },
      {
        institutie: "INSEAD",
        perioada: "2017",
        diploma: "Executive Leadership Program",
      },
    ],
    competente: ["Operational strategy", "P&L ownership", "Process optimization", "People leadership", "Change management", "Executive reporting"],
    limbi: ["English (native)", "French (intermediate)"],
    certificari: ["PMP", "Lean Six Sigma Black Belt"],
  },
  13: {
    nume: "Isla Morgan",
    titlu: "Graphic Designer / Brand Identity Designer",
    email: "isla.morgan@example.com",
    telefon: "+44 7788 400500",
    oras: "Bristol",
    linkedin: "linkedin.com/in/isla-morgan-designer",
    despre: "Graphic designer with 6 years of experience in branding, digital campaigns, and visual systems. Known for thoughtful concept work, clean execution, and strong collaboration with marketing teams and clients.",
    experienta: [
      {
        firma: "Studio Finch",
        perioada: "2021 - Present",
        rol: "Senior Graphic Designer",
        desc: "Create identity systems, campaign assets, and digital content for brand teams • Present concepts to clients and translate feedback into polished visual work • Collaborate closely with copywriters and strategists",
      },
      {
        firma: "Freelance",
        perioada: "2018 - 2021",
        rol: "Graphic Designer",
        desc: "Delivered branding, packaging, and social assets for startups and small businesses • Built style guides and reusable templates • Supported motion and launch visuals for online campaigns",
      },
    ],
    educatie: [
      {
        institutie: "University of the Arts London",
        perioada: "2014 - 2018",
        diploma: "Bachelor's Degree in Graphic Design",
      },
    ],
    competente: ["Adobe Creative Suite", "Brand identity", "Typography", "Figma", "Packaging design", "Social media design"],
    limbi: ["English (native)", "Italian (intermediate)"],
    certificari: ["Adobe Certified Professional", "Figma Advanced Workshop"],
  },
  14: {
    nume: "Lucas Bennett",
    titlu: "Full-Stack Web Developer",
    email: "lucas.bennett@example.com",
    telefon: "+1 206 555 4100",
    oras: "Seattle",
    linkedin: "linkedin.com/in/lucas-bennett-dev",
    despre: "Full-stack developer with 7 years of experience building modern web products. Strong in frontend architecture, backend APIs, and shipping reliable features with performance and accessibility in mind.",
    experienta: [
      {
        firma: "Skyline Digital",
        perioada: "2021 - Present",
        rol: "Senior Full-Stack Developer",
        desc: "Build product features across React, Node.js, and cloud services • Improve application performance and release workflows • Review code, mentor teammates, and support architecture decisions",
      },
      {
        firma: "Launch Harbor",
        perioada: "2017 - 2021",
        rol: "Full-Stack Developer",
        desc: "Delivered client-facing web apps across React, Next.js, Node.js, and PostgreSQL • Built REST and GraphQL APIs for dashboard and content platforms • Supported SEO, testing, and deployment automation",
      },
    ],
    educatie: [
      {
        institutie: "University of Washington",
        perioada: "2013 - 2017",
        diploma: "Bachelor's Degree in Computer Science",
      },
    ],
    competente: ["React", "Next.js", "Node.js", "TypeScript", "PostgreSQL", "CI/CD"],
    limbi: ["English (native)", "Spanish (basic)"],
    certificari: ["AWS Certified Developer - Associate", "MongoDB Developer Basics"],
  },
  15: {
    nume: "Nathan Cole",
    titlu: "Senior Laravel / PHP Developer",
    email: "nathan.cole@example.com",
    telefon: "+43 664 555 9900",
    oras: "Vienna",
    linkedin: "linkedin.com/in/nathan-cole-laravel",
    despre: "Senior Laravel developer with 8 years of experience building SaaS backends, APIs, and internal platforms. Focused on maintainable architecture, database performance, and fast delivery in product teams.",
    experienta: [
      {
        firma: "SaaS Forge",
        perioada: "2021 - Present",
        rol: "Senior Laravel Developer",
        desc: "Design and build Laravel services for subscription products and internal tools • Improve database performance and background job reliability • Support code reviews, testing strategy, and technical planning",
      },
      {
        firma: "Pixel Harbor",
        perioada: "2016 - 2021",
        rol: "Laravel Developer",
        desc: "Delivered PHP and Laravel features for B2B web platforms • Built payment, messaging, and cloud storage integrations • Introduced testing practices and reusable package structure across projects",
      },
    ],
    educatie: [
      {
        institutie: "University of Vienna",
        perioada: "2012 - 2016",
        diploma: "Bachelor's Degree in Software Engineering",
      },
    ],
    competente: ["Laravel", "PHP 8", "REST APIs", "MySQL optimization", "Queues and jobs", "Automated testing"],
    limbi: ["English (fluent)", "German (native)"],
    certificari: ["Zend Certified PHP Engineer", "AWS Certified Developer - Associate"],
  },
  16: {
    nume: "Ryan Scott",
    titlu: "PHP Backend Developer",
    email: "ryan.scott@example.com",
    telefon: "+34 611 455 990",
    oras: "Barcelona",
    linkedin: "linkedin.com/in/ryan-scott-php",
    despre: "Backend developer with 6 years of experience building robust PHP services and API integrations. Comfortable working with legacy systems, modern frameworks, and performance-focused backend improvements.",
    experienta: [
      {
        firma: "FinCore Systems",
        perioada: "2021 - Present",
        rol: "Senior PHP Developer",
        desc: "Maintain and extend backend services for financial operations tools • Build secure APIs and improve observability across core systems • Collaborate with QA and frontend teams on reliable releases",
      },
      {
        firma: "Commerce Stack",
        perioada: "2018 - 2021",
        rol: "PHP Developer",
        desc: "Built backend features for e-commerce platforms using Symfony and MySQL • Integrated payment and search services into existing products • Reduced query bottlenecks and improved deployment consistency",
      },
    ],
    educatie: [
      {
        institutie: "Autonomous University of Barcelona",
        perioada: "2014 - 2018",
        diploma: "Bachelor's Degree in Computer Engineering",
      },
    ],
    competente: ["PHP", "Symfony", "REST APIs", "MySQL", "Redis", "Docker"],
    limbi: ["English (fluent)", "Spanish (native)"],
    certificari: ["Symfony Certification", "AWS Solutions Architect - Associate"],
  },
  17: {
    nume: "Leo Adams",
    titlu: "Software Engineer / Programmer",
    email: "leo.adams@example.com",
    telefon: "+1 647 555 2800",
    oras: "Toronto",
    linkedin: "linkedin.com/in/leo-adams-engineer",
    despre: "Software engineer with 5 years of experience building backend services and internal platforms. Enjoys working across languages and systems with a strong focus on reliability, clean design, and shipping useful products.",
    experienta: [
      {
        firma: "Atlas Tech",
        perioada: "2021 - Present",
        rol: "Software Engineer",
        desc: "Build backend services and integrations for large-scale internal products • Contribute to architecture reviews, observability, and delivery pipelines • Support teammates through code review and pairing sessions",
      },
      {
        firma: "Bright Apps",
        perioada: "2018 - 2021",
        rol: "Junior to Mid Software Engineer",
        desc: "Developed platform features in Python and Java for enterprise tools • Added automated tests and improved deployment confidence • Participated in internal innovation projects and hackathons",
      },
    ],
    educatie: [
      {
        institutie: "University of Toronto",
        perioada: "2014 - 2018",
        diploma: "Bachelor's Degree in Computer Engineering",
      },
    ],
    competente: ["Python", "Java", "Distributed systems", "PostgreSQL", "Docker", "System design fundamentals"],
    limbi: ["English (native)", "French (intermediate)"],
    certificari: ["Google Professional Cloud Developer", "Oracle Certified Professional Java"],
  },
  18: {
    nume: "Zoey Mitchell",
    titlu: "Social Media Manager / Digital Content Creator",
    email: "zoey.mitchell@example.com",
    telefon: "+61 413 228 900",
    oras: "Melbourne",
    linkedin: "linkedin.com/in/zoey-mitchell-social",
    despre: "Social media manager with 5 years of experience building brand presence across Instagram, TikTok, LinkedIn, and paid social campaigns. Strong in content planning, reporting, and audience growth.",
    experienta: [
      {
        firma: "Glow Beauty",
        perioada: "2022 - Present",
        rol: "Senior Social Media Manager",
        desc: "Lead content strategy, channel planning, and campaign reporting across major social platforms • Grow audiences through short-form content and creator partnerships • Coordinate paid and organic calendars with design and performance teams",
      },
      {
        firma: "Spark Creative",
        perioada: "2019 - 2022",
        rol: "Social Media Specialist",
        desc: "Managed monthly content plans and campaign execution for multiple client accounts • Produced performance reports with engagement, reach, and conversion insights • Supported influencer partnerships and community management",
      },
    ],
    educatie: [
      {
        institutie: "RMIT University",
        perioada: "2015 - 2019",
        diploma: "Bachelor's Degree in Marketing and Communications",
      },
    ],
    competente: ["Content strategy", "Short-form video", "Paid social", "Community management", "Analytics reporting", "Copywriting"],
    limbi: ["English (native)", "Italian (basic)"],
    certificari: ["Meta Certified Digital Marketing Associate", "Google Analytics Certification"],
  },
};
